// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9izRO2VIgEfvy5PY7b6NbZTpbSeo1WxI',
    appId: '1:616392994996:web:3f5521ba0a13e0df0167e1',
    messagingSenderId: '616392994996',
    projectId: 'gestion-soutenance',
    authDomain: 'gestion-soutenance.firebaseapp.com',
    storageBucket: 'gestion-soutenance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6Cjjz7L_6AC7az4ii_GF7morrxH3TnY',
    appId: '1:616392994996:android:89bdbd5071e0c0400167e1',
    messagingSenderId: '616392994996',
    projectId: 'gestion-soutenance',
    storageBucket: 'gestion-soutenance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vpsfE708TtZ97UVb_LhvydIq5AXS7C0',
    appId: '1:616392994996:ios:02338ac8b6b9be380167e1',
    messagingSenderId: '616392994996',
    projectId: 'gestion-soutenance',
    storageBucket: 'gestion-soutenance.appspot.com',
    iosClientId: '616392994996-4qs7jcokvpcchttudq4a2aunlnsihhpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionDeSoutenance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vpsfE708TtZ97UVb_LhvydIq5AXS7C0',
    appId: '1:616392994996:ios:fdde538c05d6a6630167e1',
    messagingSenderId: '616392994996',
    projectId: 'gestion-soutenance',
    storageBucket: 'gestion-soutenance.appspot.com',
    iosClientId: '616392994996-vh1g2t4dvsedcddco9uhv3knlje1oq1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionDeSoutenance.RunnerTests',
  );
}
